# Generated by Django 5.2.10 on 2026-01-19 17:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DJNRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("q_raw", models.TextField()),
                ("user_constraints_json", models.JSONField(blank=True, default=dict)),
                ("category", models.CharField(default="general", max_length=30)),
                ("category_confidence", models.FloatField(default=0.0)),
                ("missing_fields_json", models.JSONField(blank=True, default=list)),
                ("clarifier_used", models.BooleanField(default=False)),
                (
                    "clarifier_questions_json",
                    models.JSONField(blank=True, default=list),
                ),
                ("clarifier_answers_json", models.JSONField(blank=True, default=list)),
                ("q_final", models.TextField(blank=True, default="")),
                ("assumptions_json", models.JSONField(blank=True, default=list)),
                ("jury_roster_json", models.JSONField(blank=True, default=list)),
                ("role_map_json", models.JSONField(blank=True, default=dict)),
                (
                    "final_label",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("final_answer", models.TextField(blank=True, default="")),
                (
                    "final_confidence",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "stop_reason",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("user_feedback", models.SmallIntegerField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LLMPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("provider", models.CharField(blank=True, default="", max_length=60)),
                ("model_id", models.CharField(max_length=160, unique=True)),
                ("enabled", models.BooleanField(default=True)),
                ("tags_json", models.JSONField(blank=True, default=list)),
                ("category_weights_json", models.JSONField(blank=True, default=dict)),
                ("cost_tier", models.CharField(blank=True, default="", max_length=30)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DJNRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_index", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("agreement", models.FloatField(blank=True, null=True)),
                (
                    "majority_label",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("improvement", models.FloatField(blank=True, null=True)),
                ("stagnation_flag", models.BooleanField(default=False)),
                (
                    "verdict_distribution_json",
                    models.JSONField(blank=True, default=dict),
                ),
                ("tldr_similarity_score", models.FloatField(blank=True, null=True)),
                ("effective_agreement_score", models.FloatField(blank=True, null=True)),
                ("handoff_tldr_json", models.JSONField(blank=True, default=dict)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="djn_db.djnrun",
                    ),
                ),
            ],
            options={
                "ordering": ["round_index"],
                "unique_together": {("run", "round_index")},
            },
        ),
        migrations.CreateModel(
            name="JurorResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("juror_id", models.CharField(max_length=4)),
                ("role", models.CharField(blank=True, default="", max_length=16)),
                (
                    "model_id_snapshot",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "verdict_label",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("tldr", models.TextField(blank=True, default="")),
                ("reasoning_json", models.JSONField(blank=True, default=list)),
                ("status", models.CharField(default="OK", max_length=16)),
                ("schema_valid", models.BooleanField(default=True)),
                ("error_msg", models.TextField(blank=True, default="")),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("token_in", models.IntegerField(blank=True, null=True)),
                ("token_out", models.IntegerField(blank=True, null=True)),
                ("cost_estimate", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="juror_responses",
                        to="djn_db.djnround",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="djn_db.llmpool",
                    ),
                ),
            ],
            options={
                "ordering": ["juror_id"],
                "unique_together": {("round", "juror_id")},
            },
        ),
        migrations.CreateModel(
            name="ModelRollingStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(default="general", max_length=30)),
                ("appearances_total", models.IntegerField(default=0)),
                ("user_accepts_total", models.IntegerField(default=0)),
                ("user_acceptance_rate", models.FloatField(default=0.0)),
                ("win_rate_in_majority", models.FloatField(default=0.0)),
                ("disagreement_rate", models.FloatField(default=0.0)),
                ("avg_latency_ms", models.FloatField(default=0.0)),
                ("schema_valid_rate", models.FloatField(default=0.0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rolling_stats",
                        to="djn_db.llmpool",
                    ),
                ),
            ],
            options={
                "ordering": ["model__name", "category"],
                "unique_together": {("model", "category")},
            },
        ),
    ]
